date: "2026-08-28"
title: "가득 찬 학생연구실을 보며"
description: |
  처음 12층 연구실을 배정받고 혼자 밀대로 바닥을 닦아가며 정리하던 때가
  엊그제 같은데, 이렇게 자리가 다 찬 연구실을 보니 기분이 묘합니다.

  함께해준 학생들에게 고맙습니다!!!
  앞으로도 이 공간에 좋은 시간들이 쌓여가기를 바랍니다.
  \n
