date: "2025-05-15"
title: "2025 스승의 날 😊"
description: |
  2025년도 스승의 날을 맞아 대학원생 및 학부연구생들과 함께 소중한 시간을 보냈습니다.
  
  학생들이 준비한 깊은 정성에 감사하며, 앞으로도 함께 성장하는 연구실이 되길 바랍니다.

  사진#1: (왼쪽부터) 정우석 인턴, 이동전 석사과정, 오병국 교수, 서지명 석사과정, 김상준 인턴, 조은영 인턴, 박지연 인턴, 백혜윤 석사과정
  \n
