date: "2025-05-27"
title: "혜윤·지명 석사과정 첫 논문 제출 기념"
description: |
  백혜윤, 서지명 석사과정의 첫 논문 제출을 축하합니다!

  두 학생은 학부연구생 시절부터 공학교육혁신사업단 학부연구생 프로그램을 통해 Graph Representation Learning을 비롯한 다양한 스터디에 참여하며 연구 역량을 쌓아왔습니다.
  이러한 과정을 거쳐 자대 대학원 진학을 결심하였고, 석사과정 1학기에 첫 논문을 제출하는 성과를 이루었습니다.

  논문 작성을 위해 몇 주 동안 고생한 두 학생의 노력에 박수를 보냅니다
  앞으로도 좋은 연구 성과가 이어지길 기대합니다.

  사진#1: (왼쪽부터) 오병국 교수, 서지명 석사과정, 백혜윤 석사과정
  \n