
export const profiles_faculty = [
    {
        image: "/professor.jpg",
        name: "Byungkook Oh (오병국)",
        title: "Professor/Director",
        period: "2024.03 - Current",
        interest: "Graph Machine Learning, Reasoning over Graphs, Knowledge-based Systems",
        email: "bkoh@konkuk.ac.kr, bkoh509@gmail.com",
        homepage: "https://bkoh509.github.io",
    },
];

export const profiles_graduate = [
    {
        image: "/members/ku_basic_1_down.png",
        name: "Jane Smith",
        title: "Research Scientist",
        period: "2015 - Present",
        interest: "Machine Learning",
        email: "jane.smith@example.com",
        homepage: "",
    },
    {
        image: "",
        name: "Alice Johnson",
        title: "Data Scientist",
        period: "2018 - Current",
        interest: "Data Science",
        email: "alice.johnson@example.com",
        homepage: "",
    },
];

export const profiles_undergraduate = [
    {
        image: "/members/formal_yunjin_kim.jpg",
        name: "Yunjin Kim (김윤진)",
        title: "Undergraduate Intern",
        period: "2024.03 - Current",
        interest: "Graph Machine Learning",
        email: "kimyunjin23@konkuk.ac.kr, yunjink008@gmail.com",
        homepage: "",
    },
    {
        image: "/members/formal_seo.jpg",
        name: "- (서지명)",
        title: "Undergraduate Intern",
        period: "2024.06 - Current",
        interest: "Graph Machine Learning",
        email: "rfyam8562@konkuk.ac.kr",
        homepage: "",
    },
    {
        image: "/members/formal_lee.jpg",
        name: "- (이영호)",
        title: "Undergraduate Intern",
        period: "2024.06 - Current",
        interest: "Graph Machine Learning",
        email: "",
        homepage: "",
    },
    {
        image: "/members/formal_hyeyoon_baek.jpg",
        name: "Hye-Yoon Baek (백혜윤)",
        title: "Undergraduate Intern",
        period: "2024.07 - Current",
        interest: "Graph Machine Learning, Natural Language Processing",
        email: "hannah100@konkuk.ac.kr",
        homepage: "",
    },
    {
        image: "",
        name: "- (정우석)",
        title: "Undergraduate Intern",
        period: "2024.07 - Current",
        interest: "Graph Machine Learning",
        email: "oseoko@naver.com",
        homepage: "",
    },
    {
        image: "/members/formal_jisang_jun.jpg",
        name: "Ji-Sang Jun (지상준)",
        title: "Undergraduate Intern",
        period: "2024.06 - Current",
        interest: "Graph Machine Learning",
        email: "wltkdwns0220@naver.com",
        homepage: "",
    },
    // {
    //     image: "/members/yunjin_kim.jpg",
    //     name: "John Doe",
    //     title: "Professor",
    //     period: "2010 - Present",
    //     interest: "Artificial Intelligence",
    //     email: "john.doe@example.com",
    //     homepage: "",
    // },
    // {
    //     image: "",
    //     name: "Jane Smith",
    //     title: "Research Scientist",
    //     period: "2015 - Present",
    //     interest: "Machine Learning",
    //     email: "jane.smith@example.com",
    //     homepage: "",
    // },
    // {
    //     image: "",
    //     name: "Alice (엘리스)",
    //     title: "Data Scientist",
    //     period: "2018 - Present",
    //     interest: "Data Science",
    //     email: "alice.johnson@example.com",
    //     homepage: "",
    // },
];