date: "2025-07-03 ~ 2025-07-31"
title: "2025 여름방학 세미나"
description: |
  혜윤, 지명, 동천 석사과정과 9월에 합류할 해윤 석사과정, 본유 박사과정이 매주 목요일마다 세미나를 진행하였습니다.

  다음과 같은 주제로 세미나를 진행했습니다.
  - 2025-07-03 (서지명 석사과정): "Instruction Tuning for Large Language Models with Graphs" 
  - 2025-07-10 (백혜윤 석사과정): "Trends in Joint Information Extraction" 
  - 2025-07-17 (이동천 석사과정): "Knowledge Graph Question Answering (KGQA)" 
  - 2025-07-24 (구해윤 예비 석사과정): "LLM-based Recommendation: From Basics to Beyond" 
  - 2025-07-31 (구본유 예비 박사과정): "Recent advances in Graph Anomaly Detection" 

  5주간 진행된 모든 세미나에 학부연구생과 멘토링 프로젝트 참여 학부생들도 함께 참석하였습니다.
  발표자들이 세미나를 체계적으로 준비하여 난이도가 높은 주제임에도 불구하고 모두가 이해하기 쉽게 전달되었습니다.
  모든 발표자 분들 수고 많으셨습니다.

  사진#2: 서지명 석사과정
  사진#4: 백혜윤 석사과정
  사진#6: 이동천 석사과정
  사진#8: 구해윤 예비 석사과정
  사진#9: 구본유 예비 박사과정
  사진#1, 3, 5, 7: 참석자 전체
  \n