date: "2025-12-17"
title: "카카오X한국정보과학회 AI 에이전트 경진대회 수상"
description: |
  우리 연구실에서 카카오X한국정보과학회 AI 에이전트 대회에서 우수상을 수상했습니다.

  우리 연구실에서는 주로 지식그래프와 GraphRAG를 연구 관점에서 접근했습니다. 
  이 기회를 통해 Graphiti 프레임워크를 활용해 그래프 데이터베이스를 구축하고 GraphRAG를 실제로 적용할 수 있었습니다.

  사진#1 (왼쪽부터): 
    지상준 인턴, 최진호 석사과정, 서지명 석사과정
  사진#2 (왼쪽부터): 
    서지명 석사과정
  사진#3, 4 (왼쪽부터):
    최진호 석사과정
  \n
