date: "2026-02-22 ~ 2026-02-26"
title: "WSDM'26 학회 참석 및 발표"
description: |
  우리 연구실은 WSDM 2026(ACM International Conference on Web Search and Data Mining)에 참석하여 
  최신 정보검색·데이터마이닝·지식관리 관련 연구 동향을 파악하고, full research paper 연구 결과 1편을 발표하였습니다.
  
  - "Image-Guided Debiasing Distillation with Preference Alignment Across Multi-News Histories"
    저자: Jimyeung Seo, Eun-Yeong Jo, Hye-Yoon Baek, Dongcheon Lee, Xiongnan Jin, Byungkook Oh
    
    http://gli.konkuk.ac.kr/publications/papers/#image-guided-debiasing-distillation-with-preference-alignment-across-multi-news-histories
  \n