date: "2025-12-23 ~ 2026-02-19"
title: "2025 Winter Seminar"
description: |
  오병국 교수, 혜윤, 지명, 동천, 해윤 석사과정 및 본유 박사과정과 3월에 합류할 진호 예비 석사과정이 매주 세미나를 진행하였습니다.

  다음과 같은 주제로 세미나를 진행했습니다.
  - 2025-12-23 (오병국 교수): "From Pointer Network to GFlowNet for Combinatorial Optimization"
  - 2026-01-06 (서지명 석사과정): "Explainability in Graph Neural Networks"
  - 2026-01-08 (백혜윤 석사과정): "Integrating Logical Rules into LLM Reasoning for Document-level Relation Extraction" 
  - 2026-01-13 (이동천 석사과정): "Question Answering over Temporal Knowledge Graphs" 
  - 2026-01-20 (최진호 예비 석사과정): "Efficient Knowledge Graph Evidence Utilization for Retrieval-Augmented Question Answering" 
  - 2026-02-12 (구해윤 석사과정): "Semantic IDs for Recommender Systems via Vector Quantization and Generative Models" 
  - 2026-02-19 (구본유 박사과정): "Recent Advances in Spectral Perspectives for Anomaly Detection" 

  겨울방학동안 진행된 모든 세미나에 학부연구생과 멘토링 프로젝트 참여 학부생들도 함께 참석하였습니다.
  발표자들이 세미나를 체계적으로 준비하여 난이도가 높은 주제였음에도 모두가 이해하기 쉽게 전달해 주었습니다.
  점차 질적으로 향상된 발표를 보니 정말 뿌듯합니다. 
  모든 발표자 및 참석자 수고 많으셨습니다.

  사진#2: 서지명 석사과정
  사진#4: 백혜윤 석사과정
  사진#6: 이동천 석사과정
  사진#8: 최진호 예비 석사과정
  사진#10: 구해윤 석사과정
  사진#12: 구본유 박사과정
  사진#1, 3, 5, 7, 9, 11: 참석자 전체
  \n