date: "2024-08-14"
title: "2024년도 1학기 종강 기념 회식"
description: |
  멘토링 프로젝트와 논문 스터디 때문에 약간 다소 늦은 2024년도 1학기 종강 기념.
  다들 고생 많았고 멘토링 프로젝트도 잘 마무리 되었습니다.
  정우석 학부생은 아쉽게 참여하지 못했습니다.

  사진#1, 사진#2: (왼쪽부터) 김윤진 인턴, 백혜윤 인턴, 오병국 교수, 박지연 인턴, 서지명 인턴, 지상준 인턴, 이영호 인턴\n