date: "2024-08-14"
title: "2024년도 1학기 종강 기념 회식"
description: |
  멘토링 프로젝트와 논문 스터디로 다소 늦어진 2024년도 1학기 종강 기념 회식을 진행하였습니다.
  
  한 학기 동안 학부연구생들 모두 고생 많았고, 멘토링 프로젝트도 성공적으로 마무리되었습니다.

  앞으로도 계속 함께 성장해나가길 바랍니다.

  ※ 정우석 학부생은 아쉽게 참여하지 못했습니다.

  사진#1, 2: (왼쪽부터) 김윤진 인턴, 백혜윤 인턴, 오병국 교수, 박지연 인턴, 서지명 인턴, 지상준 인턴, 이영호 인턴
  \n