date: "2025-11-28"
title: "학생연구실 확장이전 완료"
description: |
  기존 8명 규모에서 12명이 함께 사용할 수 있는 공간으로 학생연구실 이사를 완료하였습니다.

  학부연구생들도 언제든지 자유롭게 찾아와 열정적으로 공부하고 연구에 참여할 수 있기를 바라며,
  모두가 오래 머물고 싶을 만큼 쾌적한 환경이 꾸준히 유지되기를 희망합니다.

  사진#1: 이사 완료한 후 사무 공간
  사진#2: 이사 완료한 후 
  사진#3: 이사 완료한 후 공용 공간
  사진#4: 이사 중...
  사진#5: 이사 중...
  사진#6: 기존 학생연구실 명패
  사진#7: 기존 학생연구실에서의 풍경
  \n
