date: "2025-11-10 ~ 2025-11-14"
title: "CIKM'25 학회 참석 및 발표"
description: |
  우리 연구실은 CIKM 2025(ACM Conference on Information and Knowledge Management)에 참석하여 
  최신 정보검색·데이터마이닝·지식관리 관련 연구 동향을 파악하고, full research paper 연구 결과 1편을 발표하였습니다.
  
  - "Relation-Faceted Graph Pooling with LLM Guidance for Dynamic Span-Aware Information Extraction"
    저자: Hye-Yoon Baek, Jinho Choi, Jimyeung Seo, Dongcheon Lee, Xiongnan Jin, Byungkook Oh
  \n