date: "2026-02-12"
title: "25-2학기 종강 기념 회식"
description: |
  25-2학기 종강을 맞아 대학원 및 학부연구생들과 함께 한 학기를 마무리하는 회식 자리를 가졌습니다.
  한 학기 동안 다들 고생 많았습니다.
  이번 학기에 각자 흥미를 가진 연구 주제를 찾아가는 모습이 뿌듯했습니다.
  
  최근 연구실을 떠난 학생들의 새로운 출발을 축하하면서도, 한편으로는 아쉬운 마음이 큽니다.
  결국 어디에 있느냐보다, 좋은 논문과 프로젝트 성과를 꾸준히 만들어가는 것이 정말 중요합니다. 
  
  우리 연구실도 이번 학기 그 어디에 못지않는 성과를 만들어냈습니다. 앞으로가 더 기대됩니다.
  
  ※ 이동천 석사과정과 박상현, 이재진, 이영호 학부생은 아쉽게 참여하지 못했습니다.

  사진#1, 2 (왼쪽부터): 
    이동현 인턴, 지상준 인턴, 백혜윤 석사과정, 구해윤 석사과정, 구본유 박사과정, 
    사예원 인턴, 홍다연 인턴, 손원희 인턴, 김예은 인턴, 최환 인턴, 서지명 석사과정, 
    오병국 교수, 최진호 석사과정, 박규민 인턴, 김세영 인턴
  사진#3 (왼쪽부터): 
    구본유 박사과정, 
    사예원 인턴, 최지현 인턴, 홍다연 인턴, 손원희 인턴, 김예은 인턴, 최환 인턴, 서지명 석사과정, 오병국 교수
  사진#4 (왼쪽부터):
    오병국 교수, 최진호 석사과정, 박규민 인턴, 김세영 인턴, 이동현 인턴, 지상준 인턴, 백혜윤 석사과정, 구해윤 석사과정
  \n
