date: "2025-07-31"
title: "25-1학기 종강 및 세미나 완료 기념 회식"
description: |
  혜윤, 지명, 동천 석사과정과 9월에 합류할 해윤 석사과정과 본유 박사과정의 세미나 완료와 2025년도 1학기 종강을 기념하여 학부연구생들과 회식을 진행하였습니다.
  대학원생과 학부연구생 모두 이번 학기에도 다들 고생 많았습니다.
  이영호 학부생은 아쉽게 참여하지 못했습니다.

  사진#1 (왼쪽부터): 
    박지연 인턴, 구해윤 예비 석사과정, 백혜윤 석사과정, 정우석 인턴, 서지명 석사과정, 
    이동천 석사과정, 지상준 인턴, 오병국 교수, 최진호 인턴, 박상현 인턴,
    김상준 인턴, 김영진 인턴, 조은영 인턴, 구본유 예비 박사과정
  \n