date: "2024-08-19"
title: "공학교육혁신사업단 학부연구생 프로그램"
description: |
  - 공학교육혁신사업단에서 주최하는 교내 연구실 실습(학부연구생) 프로그램
  - 산업체 현직 멘토와 함께 스터디/연구/논문 등을 체험할 수 있는 좋은 기회
  - 주제는 Graph ML (Graph Neural Network), Natural Language Processing, Recommender Systems 등
  - 2~4주 정도의 멘토링 프로젝트 진행 및 보고서 작성

  사진#1: (왼쪽부터) 백혜윤 인턴, 오병국 교수, 정우석 인턴
  사진#2: (왼쪽부터) 오병국 교수, 박지연 연턴, 지상준 인턴
  사진#3: (왼쪽부터) 서지명 인턴, 이영호 인턴, 오병국 교수
  사진#4: (왼쪽부터) 문현우 멘티, 오병국 교수
  ...\n